---
title: 'Reproducible Research: project 01'
author: "Samiul Azam, U of Calgary"
date: "September 11, 2016"
output:
  md_document:
    variant: markdown_github
---

## Adding libraries
```{r lib, results="hide"}
library(lubridate)
library(ggplot2)
```



## Loading and preprocessing the data

```{r loading data, echo=TRUE}

# Load the database
act_data <- read.csv("activity.csv")

# Removing rows having NA values
na_rows <- !is.na(act_data[, "steps"])
no_na_data <- act_data[na_rows,]

summary(no_na_data)
dim(no_na_data)

```

## What is mean total number of steps taken per day?
```{r question 1, echo=TRUE}

# Calculate the total number of steps taken per day
total_per_day <- aggregate(data = no_na_data, steps ~ date, FUN=sum)

# Calculate and report the mean and median of the total number of steps taken per day
sprintf("MEAN of the total number of steps taken per day: %s", mean(total_per_day$steps))
sprintf("MEDIAN of the total number of steps taken per day: %s", median(total_per_day$steps))

# Make a histogram of the total number of steps taken each day
g <- ggplot(data = total_per_day, aes(x = steps))
g <- g + geom_histogram(binwidth = 1000, boundary = 0)
g <- g + xlab("Total steps per day") + ylab("Frequency") + ggtitle( "Histogram of the total number of steps taken each day")
g <- g + scale_x_continuous(breaks=seq(0,24000,1000)) + theme(axis.text.x=element_text(angle=90))
g <- g + geom_vline(aes(xintercept = mean(total_per_day$steps), color="mean"), size = 0.5)
g <- g + geom_vline(aes(xintercept = median(total_per_day$steps), color="median"), size = 0.5)
g <- g + scale_color_manual(name = "Legend", values = c(median = "blue", mean = "red"))
print(g)
```

## What is the average daily activity pattern?
```{r question 2, echo=TRUE}
avg_interval <- aggregate(data = no_na_data, steps ~ interval, FUN=mean)

temp <- sprintf("%04d", avg_interval$interval)
avg_interval$interval <- strptime(temp, format="%H%M")
avg_interval$interval <- hour(avg_interval$interval) * 60 + minute(avg_interval$interval) 

# a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
g <- ggplot(avg_interval, aes(interval, steps)) + geom_line()
g <- g + xlab("Time intervals (5 minutes)") + ylab("Number of Steps") + ggtitle( "Time series plot of the 5-minute interval and the average number of steps")
g <- g + scale_x_continuous(breaks=seq(0,1435,60)) + theme(axis.text.x=element_text(angle=90))
g <- g + geom_vline(aes(xintercept = avg_interval$interval[which.max(avg_interval$steps)], color="maximum"), size = 0.5)
g <- g + scale_color_manual(name = "Legend", values = c(maximum = "blue"))
print(g)

#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
# Answer:
h <- avg_interval$interval[which.max(avg_interval$steps)]
sprintf("Maximum steps at the interval: %s hours %s minutes",h%/%60,h%%60)

```

## Imputing missing values
```{r question 3, echo=TRUE}
# Replacing NA values with the mean for that 5-minute interval value
# So, first calculate the average steps as per interval
avg_steps_per_intterval <- aggregate(data = no_na_data, steps ~ interval, FUN=mean)
join_data <- merge(act_data,avg_steps_per_intterval, by = "interval")

# Calculate and report the total number of missing values in the dataset 
na_rows <- is.na(join_data[, "steps.x"])
sprintf("Number of NA rows: %s", sum(na_rows))

# Replacing NA values
join_data[na_rows,"steps.x"] <- join_data[na_rows,"steps.y"]

# Create a new dataset 
new_act_data <- join_data[,c(1,2,3)]
names(new_act_data) <- c("interval","steps","date")

summary(new_act_data)
dim(new_act_data)


# Make a histogram of the total number of steps taken each day
# Calculate the total number of steps taken per day
total_per_day <- aggregate(data = new_act_data, steps ~ date, FUN=sum)

g <- ggplot(data = total_per_day, aes(x = steps))
g <- g + geom_histogram(binwidth = 1000, boundary = 0)
g <- g + xlab("Total steps per day") + ylab("Frequency") + ggtitle( "Histogram of the total number of steps taken each day (After replacing NA's)")
g <- g + scale_x_continuous(breaks=seq(0,24000,1000)) + theme(axis.text.x=element_text(angle=90))
g <- g + geom_vline(aes(xintercept = mean(total_per_day$steps), color="mean"), size = 0.5)
g <- g + geom_vline(aes(xintercept = median(total_per_day$steps), color="median"), size = 0.5)
g <- g + scale_color_manual(name = "Legend", values = c(median = "blue", mean = "red"))
print(g)

# Calculate and report the mean and median of the total number of steps taken per day for the new data
sprintf("MEAN of the total number of steps taken per day: %s", mean(total_per_day$steps))
sprintf("MEDIAN of the total number of steps taken per day: %s", median(total_per_day$steps))

# Comments: There is no significant change in the Mean and the Median values of the new data compare to the first one. However, histogram of the new data contains additional frequencies in its bins.
```

## Are there differences in activity patterns between weekdays and weekends?



```{r question 4, echo=TRUE}
# Create a new factor variable in the dataset with two levels - "weekday" and "weekend" 
new_act_data$date <- as.Date(new_act_data$date)
weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
new_act_data$wdays <- factor((weekdays(new_act_data$date) %in% weekdays1), levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))

# Calculate the total average steps taken per interval (subsetting to wdays factor)
avg_interval <- aggregate(data = new_act_data, steps ~ interval + wdays, FUN=mean)

temp <- sprintf("%04d", avg_interval$interval)
avg_interval$interval <- strptime(temp, format="%H%M")
avg_interval$interval <- hour(avg_interval$interval) * 60 + minute(avg_interval$interval) 

# Make a panel plot containing a time series plot of the 5-minute interval (x-axis) and the average 
# number of steps taken, averaged across all weekday days or weekend days (y-axis).

g <- ggplot(avg_interval, aes(interval, steps)) + geom_line()
g <- g + xlab("Time intervals (5 minutes)") + ylab("Number of Steps") + ggtitle( "Activity patterns between weekdays and weekends")
g <- g + scale_x_continuous(breaks=seq(0,1435,60)) + theme(axis.text.x=element_text(angle=90))
g <- g + facet_wrap(~wdays, nrow = 2, ncol = 1)
print(g)


```

